require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StadiaController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Stadium. As you add validations to Stadium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StadiaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stadia as @stadia" do
      stadium = Stadium.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:stadia)).to eq([stadium])
    end
  end

  describe "GET show" do
    it "assigns the requested stadium as @stadium" do
      stadium = Stadium.create! valid_attributes
      get :show, {:id => stadium.to_param}, valid_session
      expect(assigns(:stadium)).to eq(stadium)
    end
  end

  describe "GET new" do
    it "assigns a new stadium as @stadium" do
      get :new, {}, valid_session
      expect(assigns(:stadium)).to be_a_new(Stadium)
    end
  end

  describe "GET edit" do
    it "assigns the requested stadium as @stadium" do
      stadium = Stadium.create! valid_attributes
      get :edit, {:id => stadium.to_param}, valid_session
      expect(assigns(:stadium)).to eq(stadium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stadium" do
        expect {
          post :create, {:stadium => valid_attributes}, valid_session
        }.to change(Stadium, :count).by(1)
      end

      it "assigns a newly created stadium as @stadium" do
        post :create, {:stadium => valid_attributes}, valid_session
        expect(assigns(:stadium)).to be_a(Stadium)
        expect(assigns(:stadium)).to be_persisted
      end

      it "redirects to the created stadium" do
        post :create, {:stadium => valid_attributes}, valid_session
        expect(response).to redirect_to(Stadium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stadium as @stadium" do
        post :create, {:stadium => invalid_attributes}, valid_session
        expect(assigns(:stadium)).to be_a_new(Stadium)
      end

      it "re-renders the 'new' template" do
        post :create, {:stadium => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stadium" do
        stadium = Stadium.create! valid_attributes
        put :update, {:id => stadium.to_param, :stadium => new_attributes}, valid_session
        stadium.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested stadium as @stadium" do
        stadium = Stadium.create! valid_attributes
        put :update, {:id => stadium.to_param, :stadium => valid_attributes}, valid_session
        expect(assigns(:stadium)).to eq(stadium)
      end

      it "redirects to the stadium" do
        stadium = Stadium.create! valid_attributes
        put :update, {:id => stadium.to_param, :stadium => valid_attributes}, valid_session
        expect(response).to redirect_to(stadium)
      end
    end

    describe "with invalid params" do
      it "assigns the stadium as @stadium" do
        stadium = Stadium.create! valid_attributes
        put :update, {:id => stadium.to_param, :stadium => invalid_attributes}, valid_session
        expect(assigns(:stadium)).to eq(stadium)
      end

      it "re-renders the 'edit' template" do
        stadium = Stadium.create! valid_attributes
        put :update, {:id => stadium.to_param, :stadium => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stadium" do
      stadium = Stadium.create! valid_attributes
      expect {
        delete :destroy, {:id => stadium.to_param}, valid_session
      }.to change(Stadium, :count).by(-1)
    end

    it "redirects to the stadia list" do
      stadium = Stadium.create! valid_attributes
      delete :destroy, {:id => stadium.to_param}, valid_session
      expect(response).to redirect_to(stadia_url)
    end
  end

end
